### ISSUE TITLE
这些例子其实还是很疑惑的，主要是example文件文件夹里面的例子并不能解决引导问题。

### ISSUE THREAD

**Issue by neikvon** [fbi-js/factory-node#11]
这些例子其实还是很疑惑的，主要是example文件文件夹里面的例子并不能解决引导问题。
在研发同学想快速quick start的时候会很奇怪。

1. example建议不要放到项目里面，单独放一个。mrapi里面内部依赖了非常多的模块，但example的dependents没有提现。
2. 上面`npx fbi create factory-node`产生的模板无论版本、命令都会遇到问题，还不如直接写copy example

__Originally posted by @wxqqh in https://github.com/mrapi-js/mrapi/issues/80#issuecomment-850402533__

**Comment by taomas** [comment]
问题2已修复，`npx fbi create factory-node`创建项目后，执行命令遇到问题的情况已修复，目前已测试模板：

 - app template
 - service template
 - gateway template
